package lexer;
 
/**
 *  This file is automatically generated
 *  - it contains the enumeration of all of the tokens
 */
public enum Tokens {
    BogusToken,Program,Int,Fl,BOOLean,
    If,Then,Else,While,Function,
    Return,Repeat,Identifier,INTeger,Float,
    LeftBrace,RightBrace,LeftParen,RightParen,Comma,
    Assign,Equal,NotEqual,Less,LessEqual,
    Plus,Minus,Or,And,Multiply,
    Divide,Comment
}
